### ISSUE TITLE
Numpy version dependency update? 

### ISSUE THREAD

**Issue by bryan-garcia** [freegs-plasma/FreeQDSK#10]
It seems that the freeqdsk package sets a minimum numpy version of `1.8` in `pyproject.toml` yet uses the `numpy.typing` module [which was introduced in `1.20` ](https://numpy.org/devdocs/reference/typing.html). This could cause some issues downstream for applications not enforcing the `numpy>=1.20` requirement

**Comment by ZedThree** [comment]
Oops, thanks for catching this @bryan-garcia!
