### ISSUE TITLE
orientation of coordinate system 

### ISSUE THREAD

**Issue by mwiesenberger** [freegs-plasma/FreeQDSK#11]
Hi, 
it's not really an issue of the code but rather of documentation regarding the orientation of the magnetic field in an eqdsk file. 
The question is maybe also if this is even standardized or every code does what they think is best ... 

Does geqdsk data base on Cylindrical right handed coordinate system $R,\varphi,Z$ (i.e. $\hat e_\varphi$ is **anti-clock wise** if viewed from the top) 
and the magnetic field is given by
$\vec B = \frac{1}{R}\left( F \hat e_\varphi + \vec \nabla \Psi \times \hat e_\varphi \right) = \frac{1}{R}\left( F \hat e_\varphi - \frac{\partial \Psi}{\partial Z} \hat e_R + \frac{\partial \Psi}{\partial R} \hat e_Z \right)$
and $I = -2\pi F$ is the net poloidal current and $\psi_p = 2\pi \Psi$ is the poloidal flux. I am assuming that it is $\psi_p$ (not $\Psi$) that is stored in the psi variable https://freeqdsk.readthedocs.io/en/stable/geqdsk.html which means one has to divide by $2\pi$ and then derive to get the poloidal field.

If you can confirm that this is the case could this information be part of the documentation? I have an eqdsk file and need to reconstruct the magnetic field and since the $B_R$ and $B_Z$ are not part of the file, I have no consistency check, other than the q-factor maybe. Mine is negative, the `qpsi` in the file is positive, so now I'm at an impasse. Are there conventions regarding the sign of q? Is the q-profile positive for right handed field line winding and negative if left-handed?

Thanks for any information 
Best regards
Matthias

**Comment by bendudson** [comment]
Hi @mwiesenberger ! 
I think this is related to issue #9 and to an earlier discussion of the COCOS convention in FreeGS (from which FreeQDSK was derived): https://github.com/freegs-plasma/freegs/issues/59

I'm quite sure (90%?) that FreeGS defines toroidal angle as anti-clockwise if viewed from the top, like EFIT. Other codes don't follow this convention, and unfortunately the direction of the toroidal angle isn't stored in the geqdsk file. Some information on conventions and codes that follow them is here: https://crppwww.epfl.ch/~sauter/cocos/

I agree this should be in the documentation, and ideally FreeQDSK should handle different COCOS convention inputs and outputs.

Best regards,
Ben

**Comment by mwiesenberger** [comment]
Hi @bendudson,

thanks for the reading I think it clarifies a few issues I had. I created a pull-request for documentation answering also my above question on q. From my side this issue can be closed then.
All the best
Matthias
