### ISSUE TITLE
Could simplify implementation using fortranformat

### ISSUE THREAD

**Issue by LiamPattinson** [freegs-plasma/FreeQDSK#2]
The library [`fortranformat`](https://pypi.org/project/fortranformat/) could be used to simplify the reading/writing of these files. Rather than using `ChunkOutput`, `f2s`, `write_1d` etc, we could use something like the following:

```python
>>> import fortranformat as ff
>>> import numpy as np
>>> 
>>> writer = ff.FortranRecordWriter("(5e16.9)")
>>> print(writer.write(np.linspace(-1e2, 1e2, 23)))
-0.100000000E+03-0.909090909E+02-0.818181818E+02-0.727272727E+02-0.636363636E+02
-0.545454545E+02-0.454545455E+02-0.363636364E+02-0.272727273E+02-0.181818182E+02
-0.909090909E+01 0.142108547E-13 0.909090909E+01 0.181818182E+02 0.272727273E+02
 0.363636364E+02 0.454545455E+02 0.545454545E+02 0.636363636E+02 0.727272727E+02
 0.818181818E+02 0.909090909E+02 0.100000000E+03
```

`write_2d` could be replaced by `writer.write(np.asarray(val).T.ravel())`

**Comment by ZedThree** [comment]
See https://github.com/freegs-plasma/freegs/pull/80 :)

**Comment by LiamPattinson** [comment]
Oh cool, that makes things easier. I'm currently trying to avoid changing the code too much, and instead focusing on getting the [docs improved](https://github.com/freegs-plasma/FreeQDSK/pull/3). I'd be happy to replicate the work done there for a later release.

**Comment by ZedThree** [comment]
Done in #4
